version: '3.9'
services:
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    expose:
      - "5432"
  proxy:
    image: 'cactus4docker/go-camo:latest'
    restart: always
