version: '3.9'
services:
  database:
    image: 'postgres:15.2'
    restart: always
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "5432:5432"
  backend:
    image: "backend"
    build: "backend"
    depends_on:
      - database
    restart: always
    env_file: .env
    user: "node"
    environment:
      - NODE_ENV=production
    expose:
      - "${BACKEND_LISTEN_PORT}"
    ports:
      - "${BACKEND_LISTEN_PORT}:${BACKEND_LISTEN_PORT}"
  frontend:
    image: "frontend"
    env_file: .env
    build:
      context: frontend
      args:
        SSL: $SSL
        FRONTEND_ADDRESS: $FRONTEND_ADDRESS
        BACKEND_ADDRESS: $BACKEND_ADDRESS
        BOUNCER_ADDRESS: $BOUNCER_ADDRESS
    environment:
      VITE_BACKEND_ADDRESS: $BACKEND_ADDRESS
      VITE_FRONTEND_ADDRESS: $FRONTEND_ADDRESS
      VITE_BOUNCER_ADDRESS: $BOUNCER_ADDRESS
      VITE_SSL: $SSL
    depends_on:
      - backend
    restart: always
    ports:
      - "${FRONTEND_LISTEN_PORT}:80"
  proxy:
    image: 'hyxogen/bouncer:latest'
    restart: always
    env_file: .env
    expose:
      - "${BOUNCER_LISTEN_PORT}"
    environment:
      BOUNCER_PORT: $BOUNCER_LISTEN_PORT
    ports:
      - "${BOUNCER_LISTEN_PORT}:${BOUNCER_LISTEN_PORT}"
  rambler:
    image: 'dutchen18/rambler:latest'
    env_file: .env
    restart: always
    depends_on:
      - backend
