version: '3.9'
services:
  database:
    image: 'postgres:latest'
    restart: always
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
        #  backend:
        #    image: backend/
        #    env_file: .env
        #    ports:
        #      - "${BACKEND_PORT}:${BACKEND_PORT}"
        #    expose:
        #      - "${BACKEND_PORT}"
  proxy:
    image: 'hyxogen/bouncer:latest'
    restart: always
    env_file: .env
    ports:
      - "${BOUNCER_PORT}:${BOUNCER_PORT}"
    expose:
      - "${BOUNCER_PORT}"
  rambler:
    image: 'rambler'
    build: 'rambler'
    env_file: .env
    restart: always
    extra_hosts: # TODO: veranderen zodra frontend en backend ook containers zijn
      - "host.docker.internal:host-gateway"
  nginx:
    image: 'nginx:latest'
    restart: always
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # TODO: andere directory voor certs
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    extra_hosts: # TODO: veranderen zodra frontend en backend ook containers zijn
      - "host.docker.internal:host-gateway"
