version: '3.9'
services:
  database:
    image: 'postgres:latest'
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
  proxy:
    image: 'hyxogen/bouncer:latest'
    restart: always
    env_file: .env
    ports:
      - "${BOUNCER_PORT}:${BOUNCER_PORT}"
    expose:
      - "${BOUNCER_PORT}"
