version: '3.9'
services:
  database:
    image: 'postgres:latest'
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
        #  backend:
        #    image: backend/
        #    env_file: .env
        #    ports:
        #      - "${BACKEND_PORT}:${BACKEND_PORT}"
        #    expose:
        #      - "${BACKEND_PORT}"
  # proxy:
  #   image: 'hyxogen/bouncer:latest'
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - "${BOUNCER_PORT}:${BOUNCER_PORT}"
  #   expose:
  #     - "${BOUNCER_PORT}"
