version: '3.9'
services:
  database:
    image: 'postgres:15.2'
    restart: always
    env_file: .postgres.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  backend:
    image: "node:19.9"
    depends_on:
      - database
    restart: always
    env_file:
      - hosts.env
      - .postgres.env
      - .backend.env
      - .bouncer.env
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run start:prod"
  frontend:
    image: "frontend"
    build:
      context: frontend
      args:
        SSL: $SSL
        FRONTEND_ADDRESS: $FRONTEND_ADDRESS
        BACKEND_ADDRESS: $BACKEND_ADDRESS
        BOUNCER_ADDRESS: $BOUNCER_ADDRESS
    env_file:
      - hosts.env
    depends_on:
      - backend
    restart: always
    ports:
      - "5173:80"
  proxy:
    image: 'hyxogen/bouncer:latest'
    restart: always
    env_file: .bouncer.env
    expose:
      - "8080"
    ports:
      - "8080:8080"
        #  rambler:
        #    image: 'rambler'
        #    build: 'rambler'
        #    env_file: .rambler.env
        #    restart: always
        #    depends_on:
        #      - backend

